// TWC album catalog — single source of truth
// To add an album, run: npm run add-album "Artist" "Album"
const CATALOG = [
  {
    id: 'victony-stubborn',
    tidalId: 424096016,
    name: "Stubborn",
    artist: "Victony",
    release_date: "2024-06-21",
    label: "Encore Recordings",
    images: [{ url: '/twc-vinyl-shelf/covers/stubborn.jpg' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Oshaprapra",
      duration_ms: 190000,
      artists: "Victony, Shorae Moore",
    },
    {
      id: 't-2',
      track_number: 2,
      name: "History",
      duration_ms: 175000,
      artists: "Victony",
    },
    {
      id: 't-3',
      track_number: 3,
      name: "Ludo",
      duration_ms: 212000,
      artists: "Victony, Shallipopi",
    },
    {
      id: 't-4',
      track_number: 4,
      name: "Anita",
      duration_ms: 183000,
      artists: "Victony",
    },
    {
      id: 't-5',
      track_number: 5,
      name: "Everything",
      duration_ms: 167000,
      artists: "Victony",
    },
    {
      id: 't-6',
      track_number: 6,
      name: "Risk",
      duration_ms: 203000,
      artists: "Victony",
    },
    {
      id: 't-7',
      track_number: 7,
      name: "Tiny Apartment",
      duration_ms: 221000,
      artists: "Victony, SAINt JHN",
    },
    {
      id: 't-9',
      track_number: 9,
      name: "Stubborn",
      duration_ms: 176000,
      artists: "Victony, Asake",
    },
    {
      id: 't-10',
      track_number: 10,
      name: "Kolo (Kolomental II)",
      duration_ms: 166000,
      artists: "Victony",
    },
    {
      id: 't-11',
      track_number: 11,
      name: "Ba$Tard, Don't Be Silly",
      duration_ms: 172000,
      artists: "Victony",
    },
    {
      id: 't-12',
      track_number: 12,
      name: "Pier 46",
      duration_ms: 159000,
      artists: "Victony, Ktizo",
    },
    {
      id: 't-13',
      track_number: 13,
      name: "Sunday School",
      duration_ms: 183000,
      artists: "Victony",
    },
    {
      id: 't-14',
      track_number: 14,
      name: "Street Affair",
      duration_ms: 172000,
      artists: "Victony",
    },
    ],
    credits: [
      { name: 'Victony', role: 'Vocals, songwriter' },
      { name: 'Shallipopi', role: 'Featured artist (track 3)' },
      { name: 'Rema', role: 'Featured artist (track 4)' },
      { name: 'Asake', role: 'Featured artist (track 9)' },
      { name: 'Davido', role: 'Featured artist (track 12)' },
      { name: 'P.Priime', role: 'Producer' },
      { name: 'Tempoe', role: 'Producer' },
      { name: 'Blaise Beatz', role: 'Producer' },
      { name: 'Ktizo', role: 'Producer' },
      { name: 'BigFish', role: 'Producer' },
      { name: 'Dera', role: 'Producer' },
      { name: 'E Kelly', role: 'Producer' },
      { name: 'London', role: 'Producer' },
      { name: 'Vstix', role: 'Producer' },
      { name: 'Tyler Chase', role: 'Mixing engineer (tracks 6, 7, 8, 10)' },
      { name: 'Milla', role: 'Mixing engineer' },
      { name: 'STG', role: 'Mixing engineer' },
      { name: 'Josh Gudwin', role: 'Mixing engineer' },
      { name: 'Colin Leonard', role: 'Mastering engineer' },
    ],
  },
]

export default CATALOG
