// TWC album catalog — single source of truth
// To add an album/single, run: npm run add-album "Artist" "Title"
const CATALOG = [
{
    id: 'victony-stubborn',
    name: "Stubborn",
    artist: "Victony",
    release_date: "2024-06-21",
    label: "Encore Recordings",
    images: [{ url: '/twc-vinyl-shelf/covers/stubborn.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Oshaprapra",
      duration_ms: 189897,
      artists: "Victony, Shorae Moore",
    },
    {
      id: 't-2',
      track_number: 2,
      name: "History",
      duration_ms: 174666,
      artists: "Victony",
    },
    {
      id: 't-3',
      track_number: 3,
      name: "Ludo",
      duration_ms: 212041,
      artists: "Victony, Shallipopi",
    },
    {
      id: 't-4',
      track_number: 4,
      name: "Anita",
      duration_ms: 183374,
      artists: "Victony",
    },
    {
      id: 't-5',
      track_number: 5,
      name: "Everything",
      duration_ms: 166958,
      artists: "Victony",
    },
    {
      id: 't-6',
      track_number: 6,
      name: "Risk",
      duration_ms: 202958,
      artists: "Victony",
    },
    {
      id: 't-7',
      track_number: 7,
      name: "Tiny Apartment",
      duration_ms: 220865,
      artists: "Victony, SAINt JHN",
    },
    {
      id: 't-8',
      track_number: 8,
      name: "Slow Down",
      duration_ms: 170769,
      artists: "Victony, Teezo Touchdown",
    },
    {
      id: 't-9',
      track_number: 9,
      name: "Stubborn",
      duration_ms: 176333,
      artists: "Victony, Asake",
    },
    {
      id: 't-10',
      track_number: 10,
      name: "Kolo (Kolomental II)",
      duration_ms: 166458,
      artists: "Victony",
    },
    {
      id: 't-11',
      track_number: 11,
      name: "Ba$tard, Don't Be Silly",
      duration_ms: 171666,
      artists: "Victony",
    },
    {
      id: 't-12',
      track_number: 12,
      name: "Pier 46",
      duration_ms: 158833,
      artists: "Victony, Ktizo",
    },
    {
      id: 't-13',
      track_number: 13,
      name: "Sunday School",
      duration_ms: 183000,
      artists: "Victony",
    },
    {
      id: 't-14',
      track_number: 14,
      name: "Street Affair",
      duration_ms: 172333,
      artists: "Victony",
    },
    ],
    credits: [
      // Vocals
      { name: 'Anthony "Victony" Victor', role: 'Vocals, writer (all tracks)' },
      { name: 'Adekunle "Shorae Moore" Seyi', role: 'Vocals, writer (track 1)' },
      { name: 'Crown "Shallipopi" Uzama', role: 'Vocals, writer (track 3)' },
      { name: 'DeepXpressions Choir', role: 'Background vocals (tracks 4, 14)' },
      { name: 'Melissa Montgomery', role: 'Background vocals (track 6)' },
      { name: 'Aaron "Teezo Touchdown" Thomas', role: 'Vocals, writer (track 8)' },
      { name: 'Ahmed "Asake" Ololade', role: 'Vocals, writer (track 9)' },
      { name: 'Carlos "Saint Jhn" Phillips', role: 'Vocals, writer (track 7)' },
      // Engineering
      { name: 'Leandro "Dro" Hidalgo', role: 'Mixing engineer (track 4)' },
      { name: 'Tyler Chase', role: 'Mixing engineer (tracks 6, 7, 8, 10)' },
      { name: 'Peter A. Barker', role: 'Spatial mixing engineer (track 5)' },
      { name: 'Sam Harper', role: 'Mixing engineer (track 13)' },
      { name: 'Liz Robson', role: 'Recording engineer (track 9)' },
      { name: 'Chuma "Hoodini" Nwokeke (of Ktizo)', role: 'Writer, mixing engineer, mastering engineer (tracks 1–14)' },
      // Writers
      { name: 'Oluseni "IamDJNotorious" Oyinlola (of Ktizo)', role: 'Writer (tracks 1, 2, 5, 9, 11, 12, 14)' },
      { name: 'Mac Sutphin (of 1Mind)', role: 'Writer (tracks 9, 10)' },
      { name: 'Sebastián López (of 1Mind)', role: 'Writer (track 9)' },
      { name: 'Carter Lang', role: 'Writer (track 5)' },
      { name: 'William Walsh', role: 'Writer (track 5)' },
      { name: 'Austin "Post Malone" Post', role: 'Writer (track 5)' },
      { name: 'Carl Rosen', role: 'Writer (track 5)' },
      { name: 'Khalif "Swae Lee" Brown', role: 'Writer (track 5)' },
      { name: 'Temitope Salami', role: 'Writer (track 5)' },
      { name: 'Louis Amon Josek (of 255)', role: 'Writer (track 11)' },
      { name: 'Charles Malo Josek (of 255)', role: 'Writer (track 11)' },
      { name: 'Guy Solomon Josek (of 255)', role: 'Writer (track 11)' },
      // Producers
      { name: 'Ktizo', role: 'Producer (tracks 1, 2, 9, 12, 14)' },
      { name: 'Richard "P2J" Isong', role: 'Producer, writer (tracks 3, 4, 13)' },
      { name: 'Gaetan Judd', role: 'Producer, writer (tracks 4, 13)' },
      { name: 'Marcel "Blaisebeatz" Akunwata', role: 'Producer, writer (track 5)' },
      { name: 'Louis Bell', role: 'Writer, producer (tracks 5, 10)' },
      { name: 'Paul Jefferies', role: 'Producer, writer (track 8)' },
      { name: 'Mob Beatz', role: 'Producer (track 7)' },
      { name: 'Tommy Brown', role: 'Producer (track 7)' },
      { name: 'Tommy Parker', role: 'Producer (track 7)' },
      { name: '1Mind', role: 'Producer (tracks 9, 10)' },
      { name: 'Westen Weiss', role: 'Producer, writer (tracks 9, 10)' },
      { name: 'Brendan Grieve', role: 'Producer (track 10)' },
      { name: '255', role: 'Producer (track 11)' },
      { name: 'Brandon "Fritz" Sully', role: 'Producer, writer (track 12)' },
      { name: 'Harrison "Harry" Song', role: 'Producer, writer (tracks 12, 14)' },
      { name: 'Cole Misola', role: 'Producer, writer (track 14)' },
    ],
  },
  {
    id: 'ebk-jaaybo-boogieman',
    name: "Boogieman",
    artist: "EBK JaayBo",
    release_date: "2024-08-22",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/boogieman.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Boogieman",
      duration_ms: 216840,
      artists: "EBK JaayBo",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Mixing engineer" },
    ],
  },
  {
    id: 'ebk-jaaybo-f-ck-everybody-free-maxx',
    name: "F*ck Everybody (Free Maxx)",
    artist: "EBK JaayBo",
    release_date: "2025-03-07",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/f-ck-everybody-free-maxx.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "F*ck Everybody (Free Maxx)",
      duration_ms: 190007,
      artists: "EBK JaayBo",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'ebk-jaaybo-5k',
    name: "5K",
    artist: "EBK JaayBo",
    release_date: "2025-09-05",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/5k.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "5K",
      duration_ms: 128000,
      artists: "EBK JaayBo",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'ebk-jaaybo-the-biggest-g',
    name: "The Biggest G",
    artist: "EBK JaayBo",
    release_date: "2025-02-18",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/the-biggest-g.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "The Biggest G",
      duration_ms: 0,
      artists: "EBK JaayBo",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'victony-v-s-freestyle',
    name: "V.S. Freestyle",
    artist: "Victony",
    release_date: "2025-11-21",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/v-s-freestyle.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "V.S. Freestyle",
      duration_ms: 0,
      artists: "Victony",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Engineer, mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'nardo-wick-burning-up-feat-the-kid-laroi',
    name: "Burning Up (feat. The Kid LAROI)",
    artist: "Nardo Wick",
    release_date: "2022-07-22",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/burning-up-feat-the-kid-laroi.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Burning Up (feat. The Kid LAROI)",
      duration_ms: 128840,
      artists: "Nardo Wick",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Engineer" },
    ],
  },
  {
    id: 'girlfriend-deep',
    name: "Deep",
    artist: "Girlfriend",
    release_date: "2025-12-17",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/deep.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Deep",
      duration_ms: 161663,
      artists: "Girlfriend",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Engineer" },
    ],
  },
  {
    id: 'victony-e-go-be',
    name: "E Go Be",
    artist: "Victony & Don Jazzy",
    release_date: "2025-11-21",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/e-go-be.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "E Go Be",
      duration_ms: 0,
      artists: "Victony & Don Jazzy",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Engineer" },
    ],
  },
  {
    id: 'ebk-jaaybo-long-live-my-brother',
    name: "Long Live My Brother",
    artist: "EBK JaayBo",
    release_date: "2025-04-11",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/long-live-my-brother.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Long Live My Brother",
      duration_ms: 202667,
      artists: "EBK JaayBo",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'ebk-jaaybo-someone-you-love',
    name: "Someone You Love",
    artist: "EBK JaayBo",
    release_date: "2025-07-18",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/someone-you-love.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Someone You Love",
      duration_ms: 242824,
      artists: "EBK JaayBo",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'ebk-jaaybo-i-m-koming',
    name: "I'm Koming",
    artist: "EBK JaayBo",
    release_date: "2025-08-22",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/i-m-koming.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "I'm Koming",
      duration_ms: 0,
      artists: "EBK JaayBo",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'blp-kosher-hour-glass',
    name: "Hour Glass",
    artist: "BLP Kosher",
    release_date: "2024-07-12",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/hour-glass.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Hour Glass",
      duration_ms: 0,
      artists: "BLP Kosher",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Composer, mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'fivio-foreign-paris-to-tokyo',
    name: "Paris to Tokyo",
    artist: "Fivio Foreign & The Kid LAROI",
    release_date: "2022-07-08",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/paris-to-tokyo.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Paris to Tokyo",
      duration_ms: 130897,
      artists: "Fivio Foreign & The Kid LAROI",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Engineer" },
    ],
  },
  {
    id: 'mike-dimes-off-the-porch-feat-bigxthaplug-maxo-kream',
    name: "OFF THE PORCH (feat. BigXthaPlug & Maxo Kream)",
    artist: "Mike Dimes",
    release_date: "2023-04-21",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/off-the-porch-feat-bigxthaplug-maxo-kream.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "OFF THE PORCH (feat. BigXthaPlug & Maxo Kream)",
      duration_ms: 230214,
      artists: "Mike Dimes",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Engineer" },
    ],
  },
  {
    id: 'saul-villarreal-como-yo',
    name: "Como Yo",
    artist: "Saul Villarreal",
    release_date: "2024-05-29",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/como-yo.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Como Yo",
      duration_ms: 211892,
      artists: "Saul Villarreal",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Mastering engineer, mixing engineer" },
    ],
  },
  {
    id: 'blp-kosher-skidoo',
    name: "Skidoo",
    artist: "BLP Kosher",
    release_date: "2024-07-12",
    label: "",
    images: [{ url: '/twc-vinyl-shelf/covers/skidoo.webp' }],
    tracks: [
    {
      id: 't-1',
      track_number: 1,
      name: "Skidoo",
      duration_ms: 0,
      artists: "BLP Kosher",
    },
    ],
    credits: [
      { name: "Tyler Chase", role: "Engineer, mastering engineer, mixing engineer" },
    ],
  },
]

export default CATALOG
