// Built-in album catalog for browsing
// Covers are placeholder gradient-based — no external API needed
const DEMO_CATALOG = [
  {
    id: 'demo-1',
    name: 'Kind of Blue',
    artist: 'Miles Davis',
    release_date: '1959-08-17',
    total_tracks: 5,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't1-1', name: 'So What', track_number: 1, duration_ms: 562000, uri: null, artists: 'Miles Davis' },
      { id: 't1-2', name: 'Freddie Freeloader', track_number: 2, duration_ms: 588000, uri: null, artists: 'Miles Davis' },
      { id: 't1-3', name: 'Blue in Green', track_number: 3, duration_ms: 327000, uri: null, artists: 'Miles Davis' },
      { id: 't1-4', name: 'All Blues', track_number: 4, duration_ms: 694000, uri: null, artists: 'Miles Davis' },
      { id: 't1-5', name: 'Flamenco Sketches', track_number: 5, duration_ms: 566000, uri: null, artists: 'Miles Davis' },
    ],
    label: 'Columbia',
  },
  {
    id: 'demo-2',
    name: 'To Pimp a Butterfly',
    artist: 'Kendrick Lamar',
    release_date: '2015-03-15',
    total_tracks: 16,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't2-1', name: 'Wesley\'s Theory', track_number: 1, duration_ms: 289000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-2', name: 'For Free? (Interlude)', track_number: 2, duration_ms: 132000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-3', name: 'King Kunta', track_number: 3, duration_ms: 234000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-4', name: 'Institutionalized', track_number: 4, duration_ms: 274000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-5', name: 'These Walls', track_number: 5, duration_ms: 302000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-6', name: 'u', track_number: 6, duration_ms: 267000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-7', name: 'Alright', track_number: 7, duration_ms: 219000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-8', name: 'For Sale? (Interlude)', track_number: 8, duration_ms: 284000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-9', name: 'Momma', track_number: 9, duration_ms: 283000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-10', name: 'Hood Politics', track_number: 10, duration_ms: 272000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-11', name: 'How Much a Dollar Cost', track_number: 11, duration_ms: 267000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-12', name: 'Complexion (A Zulu Love)', track_number: 12, duration_ms: 277000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-13', name: 'The Blacker the Berry', track_number: 13, duration_ms: 333000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-14', name: 'You Ain\'t Gotta Lie', track_number: 14, duration_ms: 244000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-15', name: 'i', track_number: 15, duration_ms: 333000, uri: null, artists: 'Kendrick Lamar' },
      { id: 't2-16', name: 'Mortal Man', track_number: 16, duration_ms: 732000, uri: null, artists: 'Kendrick Lamar' },
    ],
    label: 'Top Dawg / Aftermath / Interscope',
  },
  {
    id: 'demo-3',
    name: 'In Rainbows',
    artist: 'Radiohead',
    release_date: '2007-10-10',
    total_tracks: 10,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't3-1', name: '15 Step', track_number: 1, duration_ms: 237000, uri: null, artists: 'Radiohead' },
      { id: 't3-2', name: 'Bodysnatchers', track_number: 2, duration_ms: 242000, uri: null, artists: 'Radiohead' },
      { id: 't3-3', name: 'Nude', track_number: 3, duration_ms: 267000, uri: null, artists: 'Radiohead' },
      { id: 't3-4', name: 'Weird Fishes/Arpeggi', track_number: 4, duration_ms: 318000, uri: null, artists: 'Radiohead' },
      { id: 't3-5', name: 'All I Need', track_number: 5, duration_ms: 227000, uri: null, artists: 'Radiohead' },
      { id: 't3-6', name: 'Faust Arp', track_number: 6, duration_ms: 132000, uri: null, artists: 'Radiohead' },
      { id: 't3-7', name: 'Reckoner', track_number: 7, duration_ms: 290000, uri: null, artists: 'Radiohead' },
      { id: 't3-8', name: 'House of Cards', track_number: 8, duration_ms: 326000, uri: null, artists: 'Radiohead' },
      { id: 't3-9', name: 'Jigsaw Falling into Place', track_number: 9, duration_ms: 247000, uri: null, artists: 'Radiohead' },
      { id: 't3-10', name: 'Videotape', track_number: 10, duration_ms: 279000, uri: null, artists: 'Radiohead' },
    ],
    label: 'XL Recordings',
  },
  {
    id: 'demo-4',
    name: 'Blonde',
    artist: 'Frank Ocean',
    release_date: '2016-08-20',
    total_tracks: 17,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't4-1', name: 'Nikes', track_number: 1, duration_ms: 314000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-2', name: 'Ivy', track_number: 2, duration_ms: 249000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-3', name: 'Pink + White', track_number: 3, duration_ms: 181000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-4', name: 'Be Yourself', track_number: 4, duration_ms: 82000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-5', name: 'Solo', track_number: 5, duration_ms: 256000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-6', name: 'Skyline To', track_number: 6, duration_ms: 195000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-7', name: 'Self Control', track_number: 7, duration_ms: 249000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-8', name: 'Good Guy', track_number: 8, duration_ms: 74000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-9', name: 'Nights', track_number: 9, duration_ms: 307000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-10', name: 'Solo (Reprise)', track_number: 10, duration_ms: 77000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-11', name: 'Pretty Sweet', track_number: 11, duration_ms: 152000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-12', name: 'Facebook Story', track_number: 12, duration_ms: 68000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-13', name: 'Close to You', track_number: 13, duration_ms: 87000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-14', name: 'White Ferrari', track_number: 14, duration_ms: 274000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-15', name: 'Seigfried', track_number: 15, duration_ms: 339000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-16', name: 'Godspeed', track_number: 16, duration_ms: 171000, uri: null, artists: 'Frank Ocean' },
      { id: 't4-17', name: 'Futura Free', track_number: 17, duration_ms: 564000, uri: null, artists: 'Frank Ocean' },
    ],
    label: 'Boys Don\'t Cry',
  },
  {
    id: 'demo-5',
    name: 'Remain in Light',
    artist: 'Talking Heads',
    release_date: '1980-10-08',
    total_tracks: 8,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't5-1', name: 'Born Under Punches (The Heat Goes On)', track_number: 1, duration_ms: 346000, uri: null, artists: 'Talking Heads' },
      { id: 't5-2', name: 'Crosseyed and Painless', track_number: 2, duration_ms: 280000, uri: null, artists: 'Talking Heads' },
      { id: 't5-3', name: 'The Great Curve', track_number: 3, duration_ms: 375000, uri: null, artists: 'Talking Heads' },
      { id: 't5-4', name: 'Once in a Lifetime', track_number: 4, duration_ms: 263000, uri: null, artists: 'Talking Heads' },
      { id: 't5-5', name: 'Houses in Motion', track_number: 5, duration_ms: 293000, uri: null, artists: 'Talking Heads' },
      { id: 't5-6', name: 'Seen and Not Seen', track_number: 6, duration_ms: 232000, uri: null, artists: 'Talking Heads' },
      { id: 't5-7', name: 'Listening Wind', track_number: 7, duration_ms: 265000, uri: null, artists: 'Talking Heads' },
      { id: 't5-8', name: 'The Overload', track_number: 8, duration_ms: 361000, uri: null, artists: 'Talking Heads' },
    ],
    label: 'Sire',
  },
  {
    id: 'demo-6',
    name: 'Vespertine',
    artist: 'Bjork',
    release_date: '2001-08-27',
    total_tracks: 12,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't6-1', name: 'Hidden Place', track_number: 1, duration_ms: 325000, uri: null, artists: 'Bjork' },
      { id: 't6-2', name: 'Cocoon', track_number: 2, duration_ms: 298000, uri: null, artists: 'Bjork' },
      { id: 't6-3', name: 'It\'s Not Up to You', track_number: 3, duration_ms: 307000, uri: null, artists: 'Bjork' },
      { id: 't6-4', name: 'Undo', track_number: 4, duration_ms: 316000, uri: null, artists: 'Bjork' },
      { id: 't6-5', name: 'Pagan Poetry', track_number: 5, duration_ms: 325000, uri: null, artists: 'Bjork' },
      { id: 't6-6', name: 'Frosti', track_number: 6, duration_ms: 110000, uri: null, artists: 'Bjork' },
      { id: 't6-7', name: 'Aurora', track_number: 7, duration_ms: 289000, uri: null, artists: 'Bjork' },
      { id: 't6-8', name: 'An Echo, a Stain', track_number: 8, duration_ms: 222000, uri: null, artists: 'Bjork' },
      { id: 't6-9', name: 'Sun in My Mouth', track_number: 9, duration_ms: 170000, uri: null, artists: 'Bjork' },
      { id: 't6-10', name: 'Heirloom', track_number: 10, duration_ms: 282000, uri: null, artists: 'Bjork' },
      { id: 't6-11', name: 'Harm of Will', track_number: 11, duration_ms: 321000, uri: null, artists: 'Bjork' },
      { id: 't6-12', name: 'Unison', track_number: 12, duration_ms: 432000, uri: null, artists: 'Bjork' },
    ],
    label: 'One Little Independent',
  },
  {
    id: 'demo-7',
    name: 'Loveless',
    artist: 'My Bloody Valentine',
    release_date: '1991-11-04',
    total_tracks: 11,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't7-1', name: 'Only Shallow', track_number: 1, duration_ms: 251000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-2', name: 'Loomer', track_number: 2, duration_ms: 239000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-3', name: 'Touched', track_number: 3, duration_ms: 57000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-4', name: 'To Here Knows When', track_number: 4, duration_ms: 314000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-5', name: 'When You Sleep', track_number: 5, duration_ms: 243000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-6', name: 'I Only Said', track_number: 6, duration_ms: 325000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-7', name: 'Come in Alone', track_number: 7, duration_ms: 232000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-8', name: 'Sometimes', track_number: 8, duration_ms: 319000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-9', name: 'Blown a Wish', track_number: 9, duration_ms: 212000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-10', name: 'What You Want', track_number: 10, duration_ms: 317000, uri: null, artists: 'My Bloody Valentine' },
      { id: 't7-11', name: 'Soon', track_number: 11, duration_ms: 404000, uri: null, artists: 'My Bloody Valentine' },
    ],
    label: 'Creation',
  },
  {
    id: 'demo-8',
    name: 'Mezzanine',
    artist: 'Massive Attack',
    release_date: '1998-04-20',
    total_tracks: 11,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't8-1', name: 'Angel', track_number: 1, duration_ms: 379000, uri: null, artists: 'Massive Attack' },
      { id: 't8-2', name: 'Risingson', track_number: 2, duration_ms: 296000, uri: null, artists: 'Massive Attack' },
      { id: 't8-3', name: 'Teardrop', track_number: 3, duration_ms: 331000, uri: null, artists: 'Massive Attack' },
      { id: 't8-4', name: 'Inertia Creeps', track_number: 4, duration_ms: 346000, uri: null, artists: 'Massive Attack' },
      { id: 't8-5', name: 'Exchange', track_number: 5, duration_ms: 247000, uri: null, artists: 'Massive Attack' },
      { id: 't8-6', name: 'Dissolved Girl', track_number: 6, duration_ms: 339000, uri: null, artists: 'Massive Attack' },
      { id: 't8-7', name: 'Man Next Door', track_number: 7, duration_ms: 349000, uri: null, artists: 'Massive Attack' },
      { id: 't8-8', name: 'Black Milk', track_number: 8, duration_ms: 374000, uri: null, artists: 'Massive Attack' },
      { id: 't8-9', name: 'Mezzanine', track_number: 9, duration_ms: 362000, uri: null, artists: 'Massive Attack' },
      { id: 't8-10', name: 'Group Four', track_number: 10, duration_ms: 491000, uri: null, artists: 'Massive Attack' },
      { id: 't8-11', name: '(Exchange)', track_number: 11, duration_ms: 63000, uri: null, artists: 'Massive Attack' },
    ],
    label: 'Virgin',
  },
  {
    id: 'demo-9',
    name: 'Dummy',
    artist: 'Portishead',
    release_date: '1994-08-22',
    total_tracks: 11,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't9-1', name: 'Mysterons', track_number: 1, duration_ms: 307000, uri: null, artists: 'Portishead' },
      { id: 't9-2', name: 'Sour Times', track_number: 2, duration_ms: 249000, uri: null, artists: 'Portishead' },
      { id: 't9-3', name: 'Strangers', track_number: 3, duration_ms: 230000, uri: null, artists: 'Portishead' },
      { id: 't9-4', name: 'It Could Be Sweet', track_number: 4, duration_ms: 246000, uri: null, artists: 'Portishead' },
      { id: 't9-5', name: 'Wandering Star', track_number: 5, duration_ms: 288000, uri: null, artists: 'Portishead' },
      { id: 't9-6', name: 'It\'s a Fire', track_number: 6, duration_ms: 234000, uri: null, artists: 'Portishead' },
      { id: 't9-7', name: 'Numb', track_number: 7, duration_ms: 234000, uri: null, artists: 'Portishead' },
      { id: 't9-8', name: 'Roads', track_number: 8, duration_ms: 304000, uri: null, artists: 'Portishead' },
      { id: 't9-9', name: 'Pedestal', track_number: 9, duration_ms: 218000, uri: null, artists: 'Portishead' },
      { id: 't9-10', name: 'Biscuit', track_number: 10, duration_ms: 302000, uri: null, artists: 'Portishead' },
      { id: 't9-11', name: 'Glory Box', track_number: 11, duration_ms: 305000, uri: null, artists: 'Portishead' },
    ],
    label: 'Go! Beat',
  },
  {
    id: 'demo-10',
    name: 'Donuts',
    artist: 'J Dilla',
    release_date: '2006-02-07',
    total_tracks: 31,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't10-1', name: 'Donuts (Outro)', track_number: 1, duration_ms: 12000, uri: null, artists: 'J Dilla' },
      { id: 't10-2', name: 'Workinonit', track_number: 2, duration_ms: 112000, uri: null, artists: 'J Dilla' },
      { id: 't10-3', name: 'Waves', track_number: 3, duration_ms: 84000, uri: null, artists: 'J Dilla' },
      { id: 't10-4', name: 'Light My Fire', track_number: 4, duration_ms: 106000, uri: null, artists: 'J Dilla' },
      { id: 't10-5', name: 'The New', track_number: 5, duration_ms: 66000, uri: null, artists: 'J Dilla' },
      { id: 't10-6', name: 'Stop', track_number: 6, duration_ms: 96000, uri: null, artists: 'J Dilla' },
      { id: 't10-7', name: 'People', track_number: 7, duration_ms: 53000, uri: null, artists: 'J Dilla' },
      { id: 't10-8', name: 'The Diff\'rence', track_number: 8, duration_ms: 80000, uri: null, artists: 'J Dilla' },
      { id: 't10-9', name: 'Mash', track_number: 9, duration_ms: 59000, uri: null, artists: 'J Dilla' },
      { id: 't10-10', name: 'Time: The Donut of the Heart', track_number: 10, duration_ms: 104000, uri: null, artists: 'J Dilla' },
    ],
    label: 'Stones Throw',
  },
  {
    id: 'demo-11',
    name: 'Endtroducing.....',
    artist: 'DJ Shadow',
    release_date: '1996-09-16',
    total_tracks: 18,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't11-1', name: 'Best Foot Forward', track_number: 1, duration_ms: 47000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-2', name: 'Building Steam with a Grain of Salt', track_number: 2, duration_ms: 395000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-3', name: 'The Number Song', track_number: 3, duration_ms: 293000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-4', name: 'Changeling / Transmission 1', track_number: 4, duration_ms: 401000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-5', name: 'What Does Your Soul Look Like (Pt. 1)', track_number: 5, duration_ms: 288000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-6', name: 'Organ Donor', track_number: 6, duration_ms: 212000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-7', name: 'Stem / Long Stem', track_number: 7, duration_ms: 433000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-8', name: 'Mutual Slump', track_number: 8, duration_ms: 349000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-9', name: 'Midnight in a Perfect World', track_number: 9, duration_ms: 303000, uri: null, artists: 'DJ Shadow' },
      { id: 't11-10', name: 'Napalm Brain / Scatter Brain', track_number: 10, duration_ms: 300000, uri: null, artists: 'DJ Shadow' },
    ],
    label: 'Mo\' Wax',
  },
  {
    id: 'demo-12',
    name: 'Homework',
    artist: 'Daft Punk',
    release_date: '1997-01-20',
    total_tracks: 16,
    uri: null,
    images: [{ url: null }],
    tracks: [
      { id: 't12-1', name: 'Daftendirekt', track_number: 1, duration_ms: 165000, uri: null, artists: 'Daft Punk' },
      { id: 't12-2', name: 'WDPK 83.7 FM', track_number: 2, duration_ms: 28000, uri: null, artists: 'Daft Punk' },
      { id: 't12-3', name: 'Revolution 909', track_number: 3, duration_ms: 334000, uri: null, artists: 'Daft Punk' },
      { id: 't12-4', name: 'Da Funk', track_number: 4, duration_ms: 329000, uri: null, artists: 'Daft Punk' },
      { id: 't12-5', name: 'Phoenix', track_number: 5, duration_ms: 298000, uri: null, artists: 'Daft Punk' },
      { id: 't12-6', name: 'Fresh', track_number: 6, duration_ms: 242000, uri: null, artists: 'Daft Punk' },
      { id: 't12-7', name: 'Around the World', track_number: 7, duration_ms: 427000, uri: null, artists: 'Daft Punk' },
      { id: 't12-8', name: 'Rollin\' & Scratchin\'', track_number: 8, duration_ms: 447000, uri: null, artists: 'Daft Punk' },
      { id: 't12-9', name: 'Teachers', track_number: 9, duration_ms: 170000, uri: null, artists: 'Daft Punk' },
      { id: 't12-10', name: 'High Fidelity', track_number: 10, duration_ms: 361000, uri: null, artists: 'Daft Punk' },
    ],
    label: 'Virgin',
  },
]

export default DEMO_CATALOG

export function searchDemoCatalog(query) {
  const q = query.toLowerCase().trim()
  if (!q) return DEMO_CATALOG
  return DEMO_CATALOG.filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      a.artist.toLowerCase().includes(q) ||
      a.label.toLowerCase().includes(q)
  )
}
